version: "3.3"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:/app/db.sqlite

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./db:/db
    environment:
      - SQLITE_DB_FILE=/db/db.sqlite
